INSERT INTO user VALUES(1, '老黄',35,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO user VALUES(2, '老刘',30,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO user VALUES(3, '小张',25,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
